spring:
  application:
    name: auth-service
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:mysql://localhost:3306/studenterpauthdb
    username: practice
    password: practice
    pool:
      enabled: true
      max-size: 30

logging:
  level:
    io:
      r2dbc: debug
    org:
      springframework:
        r2dbc: debug
        security: debug
        web:
          reactive: debug
    reactor:
      netty: debug



server:
  port: 3000
